name: kkh_events
description: "KKH Events App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  provider: ^6.1.2
  shimmer: ^3.0.0
  video_player: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

#   icons_launcher:
#   image_path: "assets/images/KKH Events.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/KKH Events.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/  
