name: kkh_events
description: "KKH Events App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  video_player: ^2.9.1
  shared_preferences: ^2.3.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  analyzer: ^6.4.1
  photo_manager: ^3.3.0
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.4

#   icons_launcher:
#   image_path: "assets/images/KKH Events.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/KKH Events.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/  
